### ISSUE TITLE
Can we test whether most of the variability in PER is explained by the other variables?

### ISSUE THREAD

**Issue by LucyMcGowan** [nedwardsthro/Thesis_Work#27]
Maybe use the `redun` function to see if this is the case? https://github.com/nedwardsthro/Thesis_Work/blob/54e700f4daf655835282e7f174a732b2cb897c2d/Final%20Paper.Rmd#L344

**Comment by nedwardsthro** [comment]
The next line talks about the redundancy analysis I performed.
