### ISSUE TITLE
Maybe this should say "so for example it accounts for the 25%..." or maybe I am misunderstanding what 25% means?

### ISSUE THREAD

**Issue by LucyMcGowan** [nedwardsthro/Thesis_Work#29]
https://github.com/nedwardsthro/Thesis_Work/blob/54e700f4daf655835282e7f174a732b2cb897c2d/Final%20Paper.Rmd#L548

**Comment by nedwardsthro** [comment]
Nope, you are right. I should clarify that is an example and not true in all cases.
